name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'  # Trigger on any feature branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (or whichever version your project requires)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      # Step 3: Cache dependencies to speed up the build
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and test the project
      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      # Step 5: (Optional) Upload the JAR file as an artifact for future use
      - name: Upload JAR artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: dnd-session-manager
          path: target/*.jar
